export const REQUEST_BOARD_CONTENT_PENDING = 'REQUEST_BOARD_CONTENT_PENDING';
export const REQUEST_BOARD_CONTENT_SUCCESS = 'REQUEST_BOARD_CONTENT_SUCCESS';
export const REQUEST_BOARD_CONTENT_FAILED = 'REQUEST_BOARD_CONTENT_FAILED';
export const UPDATE_LIST_POSITION = 'UPDATE_LIST_POSITION';
