export const REQUEST_USER_INFO_PENDING = 'REQUEST_USER_INFO_PENDING'
export const REQUEST_USER_INFO_SUCCESS = 'REQUEST_USER_INFO_SUCCESS'
export const REQUEST_USER_INFO_FAILED = 'REQUEST_USER_INFO_FAILED'
export const UPDATE_BOARDS = 'UPDATE_BOARDS'