export const REQUEST_USER_INFO_PENDING = 'REQUEST_USER_INFO_PENDING';
export const REQUEST_USER_INFO_SUCCESS = 'REQUEST_USER_INFO_SUCCESS';
export const REQUEST_USER_INFO_FAILED = 'REQUEST_USER_INFO_FAILED';
export const REQUEST_BOARD_INFO_PENDING = 'REQUEST_BOARD_INFO_PENDING';
export const REQUEST_BOARD_INFO_SUCCESS = 'REQUEST_BOARD_INFO_SUCCESS';
export const REQUEST_BOARD_INFO_FAILED = 'REQUEST_BOARD_INFO_FAILED';
export const SET_USER_INFO = 'SET_USER_INFO';
export const USER_LOGOUT = 'USER_LOGOUT';
